"""
Configuración del sistema
"""

from src.config.settings import DaveAgentSettings, get_settings
from src.config.prompts import (
    AGENT_SYSTEM_PROMPT,
    CODER_AGENT_DESCRIPTION,
    CODER_AGENT_SYSTEM_MESSAGE,
    CODE_SEARCHER_DESCRIPTION,
    CODE_SEARCHER_SYSTEM_MESSAGE,
    TASK_PLANNER_DESCRIPTION,
    TASK_PLANNER_SYSTEM_MESSAGE,
    TASK_PLANNER_UPDATER_MESSAGE,
    SUMMARIZER_SYSTEM_MESSAGE,
    TASK_COMPLETION_SUMMARY_PROMPT,
    SELECTOR_PROMPT,
    COMPLEXITY_DETECTOR_PROMPT,
    PLANNING_AGENT_DESCRIPTION,
    PLANNING_AGENT_SYSTEM_MESSAGE,
    SUMMARY_AGENT_DESCRIPTION,
    SUMMARY_AGENT_SYSTEM_MESSAGE,
)

__all__ = [
    "AGENT_SYSTEM_PROMPT",
    "DaveAgentSettings",
    "get_settings",
    "CODER_AGENT_DESCRIPTION",
    "CODER_AGENT_SYSTEM_MESSAGE",
    "CODE_SEARCHER_DESCRIPTION",
    "CODE_SEARCHER_SYSTEM_MESSAGE",
    "TASK_PLANNER_DESCRIPTION",
    "TASK_PLANNER_SYSTEM_MESSAGE",
    "TASK_PLANNER_UPDATER_MESSAGE",
    "SUMMARIZER_SYSTEM_MESSAGE",
    "TASK_COMPLETION_SUMMARY_PROMPT",
    "SELECTOR_PROMPT",
    "COMPLEXITY_DETECTOR_PROMPT",
    "PLANNING_AGENT_DESCRIPTION",
    "PLANNING_AGENT_SYSTEM_MESSAGE",
    "SUMMARY_AGENT_DESCRIPTION",
    "SUMMARY_AGENT_SYSTEM_MESSAGE",
]
