"""
System configuration
"""

from src.config.prompts import (
    AGENT_SYSTEM_PROMPT,
    CHAT_SYSTEM_PROMPT,
    CODER_AGENT_DESCRIPTION,
    CODE_SEARCHER_DESCRIPTION,
    CODE_SEARCHER_SYSTEM_MESSAGE,
    COMPLEXITY_DETECTOR_PROMPT,
    TASK_PLANNER_DESCRIPTION,
    TASK_PLANNER_SYSTEM_MESSAGE,
    TASK_PLANNER_UPDATER_MESSAGE,
    PLANNING_AGENT_DESCRIPTION,
    PLANNING_AGENT_SYSTEM_MESSAGE,
)
from src.config.settings import DaveAgentSettings, get_settings

__all__ = [
    "AGENT_SYSTEM_PROMPT",
    "CHAT_SYSTEM_PROMPT",
    "DaveAgentSettings",
    "get_settings",
    "CODER_AGENT_DESCRIPTION",
    "TASK_PLANNER_DESCRIPTION",
    "TASK_PLANNER_SYSTEM_MESSAGE",
    "TASK_PLANNER_UPDATER_MESSAGE",
    "CODE_SEARCHER_DESCRIPTION",
    "CODE_SEARCHER_SYSTEM_MESSAGE",
    "COMPLEXITY_DETECTOR_PROMPT",
    "PLANNING_AGENT_DESCRIPTION",
    "PLANNING_AGENT_SYSTEM_MESSAGE",
]
